codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "20...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
